language: node_js
node_js:
  - 'stable'
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
env:
  - CXX=g++-5
sudo: required
# safelist
branches:
  only:
  - master
  - test_branch
before_script: npm i
script:
- npm run test
